version: "3"
services:
  gunicorn:
    build:
      context: .
      dockerfile: docker/gunicorn/Dockerfile
    user: ${UID:-1000}:${UID:-1000}
    volumes:
      - ./codepen:/codepen:ro
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./codepen/static:/static:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${NGINX_PORT:-8000}:80
    depends_on:
      - gunicorn